package fr.dauphine.javaavance.phineloops.model;

public class PathOfInstance {

static String[] INSTANCE_PUBLIC={"grid_8x8_dist.0_vflip.false_hflip.false_messedup.false_id.3",
        "grid_8x8_dist.0_vflip.false_hflip.true_messedup.false_id.0",
        "grid_8x8_dist.0_vflip.false_hflip.true_messedup.false_id.1",
        "grid_8x8_dist.0_vflip.false_hflip.true_messedup.true_id.0",
        "grid_8x8_dist.0_vflip.true_hflip.false_messedup.false_id.0",
        "grid_8x8_dist.0_vflip.true_hflip.true_messedup.false_id.2",
        "grid_8x8_dist.1_vflip.false_hflip.true_messedup.false_id.1",
        "grid_8x8_dist.6_vflip.false_hflip.true_messedup.false_id.0",
        "grid_8x8_dist.6_vflip.false_hflip.true_messedup.false_id.1",
        "grid_8x8_dist.6_vflip.true_hflip.false_messedup.true_id.0",
        "grid_16x16_dist.0_vflip.false_hflip.true_messedup.false_id.1",
        "grid_16x16_dist.0_vflip.false_hflip.true_messedup.false_id.3",
        "grid_16x16_dist.0_vflip.true_hflip.false_messedup.false_id.0",
        "grid_16x16_dist.0_vflip.true_hflip.false_messedup.false_id.2",
        "grid_16x16_dist.0_vflip.true_hflip.true_messedup.false_id.0",
        "grid_16x16_dist.0_vflip.true_hflip.true_messedup.true_id.0",
        "grid_16x16_dist.1_vflip.true_hflip.false_messedup.false_id.1",
        "grid_16x16_dist.6_vflip.false_hflip.false_messedup.false_id.0",
        "grid_16x16_dist.6_vflip.false_hflip.true_messedup.false_id.1",
        "grid_16x16_dist.6_vflip.false_hflip.true_messedup.true_id.0",
        "grid_32x32_dist.0_vflip.false_hflip.false_messedup.false_id.0",
        "grid_32x32_dist.0_vflip.false_hflip.false_messedup.false_id.2",
        "grid_32x32_dist.0_vflip.true_hflip.false_messedup.false_id.1",
        "grid_32x32_dist.0_vflip.true_hflip.false_messedup.true_id.0",
        "grid_32x32_dist.0_vflip.true_hflip.true_messedup.false_id.3",
        "grid_32x32_dist.1_vflip.true_hflip.true_messedup.false_id.1",
        "grid_32x32_dist.6_vflip.false_hflip.false_messedup.true_id.0",
        "grid_32x32_dist.6_vflip.false_hflip.true_messedup.false_id.0",
        "grid_32x32_dist.6_vflip.true_hflip.false_messedup.false_id.1",
        "grid_64x64_dist.0_vflip.false_hflip.false_messedup.false_id.0",
        "grid_64x64_dist.0_vflip.false_hflip.false_messedup.false_id.3",
        "grid_64x64_dist.0_vflip.false_hflip.false_messedup.true_id.0",
        "grid_64x64_dist.0_vflip.true_hflip.false_messedup.false_id.0",
        "grid_64x64_dist.0_vflip.true_hflip.false_messedup.false_id.1",
        "grid_64x64_dist.0_vflip.true_hflip.true_messedup.false_id.2",
        "grid_64x64_dist.1_vflip.false_hflip.true_messedup.false_id.1",
        "grid_64x64_dist.6_vflip.true_hflip.false_messedup.false_id.0",
        "grid_64x64_dist.6_vflip.true_hflip.false_messedup.false_id.1",
        "grid_64x64_dist.6_vflip.true_hflip.false_messedup.true_id.0",
        "grid_128x128_dist.0_vflip.false_hflip.false_messedup.false_id.3",
        "grid_128x128_dist.0_vflip.false_hflip.true_messedup.false_id.0",
        "grid_128x128_dist.0_vflip.false_hflip.true_messedup.false_id.1",
        "grid_128x128_dist.0_vflip.true_hflip.false_messedup.false_id.2",
        "grid_128x128_dist.0_vflip.true_hflip.true_messedup.false_id.0",
        "grid_128x128_dist.0_vflip.true_hflip.true_messedup.true_id.0",
        "grid_128x128_dist.1_vflip.true_hflip.true_messedup.false_id.1",
        "grid_128x128_dist.6_vflip.false_hflip.true_messedup.true_id.0",
        "grid_128x128_dist.6_vflip.true_hflip.false_messedup.false_id.0",
        "grid_128x128_dist.6_vflip.true_hflip.true_messedup.false_id.1",
        "grid_256x256_dist.0_vflip.false_hflip.false_messedup.false_id.0",
        "grid_256x256_dist.0_vflip.false_hflip.false_messedup.false_id.2",
        "grid_256x256_dist.0_vflip.false_hflip.true_messedup.false_id.0",
        "grid_256x256_dist.0_vflip.false_hflip.true_messedup.false_id.3",
        "grid_256x256_dist.0_vflip.false_hflip.true_messedup.true_id.0",
        "grid_256x256_dist.0_vflip.true_hflip.true_messedup.false_id.1",
        "grid_256x256_dist.1_vflip.false_hflip.true_messedup.false_id.1",
        "grid_256x256_dist.6_vflip.false_hflip.false_messedup.false_id.1",
        "grid_256x256_dist.6_vflip.false_hflip.true_messedup.false_id.0",
        "grid_256x256_dist.6_vflip.true_hflip.false_messedup.true_id.0"};


static int[][] POSITIONS ={{0,0},
        {1,0},
        {1,1},
        {1,2},
        {1,3},
        {2,0},
        {2,1},
        {3,0},
        {3,1},
        {3,2},
        {3,3},
        {4,0},
        {5,0},
        {5,1},
        {5,2},
        {5,3},
        };
}
